.\" Copyright (c) 2008, 2009, 2010, 2011 Curtis Gedak.
.\" This is free software.  You may redistribute copies of it under the terms of
.\" the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
.\" There is NO WARRANTY, to the extent permitted by law.
.\"
.\" Process this file with
.\" groff -man -Tascii gparted.8
.\"
.\" Generate man page web content with
.\"      rman -f html gparted.8 > gparted_manpage.html
.\" and manually edit out hyperlinks and leave bold.
.\"
.\"
.TH GPARTED 8 "Jan 16th, 2011" gparted "GParted Manual"
.SH NAME
gparted \- GNOME Partition Editor for manipulating disk partitions.
.SH SYNOPSIS
.B gparted [device]...
.SH DESCRIPTION
The
.B gparted
application is the GNOME partition
editor for creating, reorganizing, and deleting disk partitions.

A disk device can be subdivided into one or more partitions.
The
.B gparted
application enables you to
change the partition organization on a disk device while
preserving the contents of the partition.

With
.B gparted
you can accomplish the following tasks:
.br
- Create a partition table on a disk device.
.br
- Enable and disable partition flags such as boot and hidden.
.br
- Perform actions with partitions such as create, delete,
resize, move, check, label, copy, and paste.

More documentation can be found in the application help manual,
and online at:
.br
http://gparted.org
.SH EXAMPLES
You can run
.B gparted
from a command line
and specify one or more disk devices.

For example, to start gparted with the devices /dev/sda and /dev/sdc
you would use the following command:

.B gparted
/dev/sda /dev/sdc
.SH NOTES
Editing partitions has the potential to cause LOSS of DATA.

The 
.B gparted
application is
designed to enable you to edit partitions while
reducing the risk of data loss.
The application is carefully tested and is used
by the GParted project team.
However, loss of data might occur due to software bugs,
hardware problems, or power failure.

You can help to reduce the risk of data loss by
not mounting or unmounting partitions outside of
the
.B gparted
application while
.B gparted
is running.

You are advised to BACKUP your DATA before using
the
.B gparted
application.
.SH REPORTING BUGS
Report bugs at:
.br
http://gparted.org/bugs.php
.SH AUTHOR
Manual page written by Curtis Gedak <gedakc@users.sf.net>
.SH "SEE ALSO"
.BR parted (8),
.BR fdisk (8),
.BR mkfs (8),
.BR ntfsprogs (8)
